In [1]:
!pip3 install pymysql

Collecting pymysql
  Using cached pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pymysql.cursors
import pandas as pd
import datetime
import uuid
import numpy as np
from itertools import combinations

In [3]:

# Connect to the database
db_connection = pymysql.connect(host='167.71.90.83',
                             user='testUser',
                             password='testUser123!',
                             db='sakila',
                             cursorclass=pymysql.cursors.DictCursor)

### Selecting results into a Pandas dataframe

In [4]:

qry = "SELECT * FROM film;"
#print(qry)

result = pd.read_sql(qry, con=db_connection)
result.head()

/var/folders/6d/xqywj2xx2llc_k2t6nkshrgh0000gn/T/ipykernel_20245/2981064506.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql(qry, con=db_connection)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
1,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
2,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
3,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
4,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update

In [5]:
qry = "SELECT * FROM film WHERE title LIKE '%affair%'"
films = pd.read_sql(qry, con=db_connection)
films.head()

/var/folders/6d/xqywj2xx2llc_k2t6nkshrgh0000gn/T/ipykernel_20245/2223808197.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  films = pd.read_sql(qry, con=db_connection)

,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
0,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update
1,film_id,title,description,release_year,language_id,original_language_id,rental_duration,rental_rate,length,replacement_cost,rating,special_features,last_update

In [7]:
qry = "SELECT * FROM actor;"
actor = pd.read_sql(qry, con=db_connection)
actor.head()

/var/folders/6d/xqywj2xx2llc_k2t6nkshrgh0000gn/T/ipykernel_29905/3512026895.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  actor = pd.read_sql(qry, con=db_connection)

   actor_id  first_name  last_name  last_update
0  actor_id  first_name  last_name  last_update
1  actor_id  first_name  last_name  last_update
2  actor_id  first_name  last_name  last_update
3  actor_id  first_name  last_name  last_update
4  actor_id  first_name  last_name  last_update

In [12]:
result = pd.merge(employees, salaries, how='left', left_on='emp_no', right_on='emp_no')

In [13]:
result.shape

(2844047, 9)

### Selecting results using a pymysql cursor

In [9]:

# Connect to the database
import json


con = pymysql.connect(host='167.71.90.83',
                             user='testUser',
                             password='testUser123!',
                             db='sakila',
                             cursorclass=pymysql.cursors.DictCursor)
data = []
try:

    with con.cursor() as cur:

        cur.execute('SELECT * FROM film LIMIT 20;')

        rows = cur.fetchall()

        for row in rows:
            film = {}
            film['film_id'] = row['film_id']
            film['title'] = row['title']
            film['description'] = row['description']
            #print(row['film_id'], row['title'], row['description'])
            data.append(film)

finally:

    con.close()
    
print(json.dumps(data))

[{"film_id": 1, "title": "ACADEMY DINOSAUR", "description": "A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies"}, {"film_id": 2, "title": "ACE GOLDFINGER", "description": "A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China"}, {"film_id": 3, "title": "ADAPTATION HOLES", "description": "A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory"}, {"film_id": 4, "title": "AFFAIR PREJUDICE", "description": "A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank"}, {"film_id": 5, "title": "AFRICAN EGG", "description": "A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico"}, {"film_id": 6, "title": "AGENT TRUMAN", "description": "A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China"}, {"film_id": 7, "title": "AIRPLANE SIERRA", "description": "A Touching Saga of a Hunter And a Butler who must Discover a Butler in A Jet Boat"}, {"film_id": 8, "title": "AIRPORT POLLOCK", "description": "A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India"}, {"film_id": 9, "title": "ALABAMA DEVIL", "description": "A Thoughtful Panorama of a Database Administrator And a Mad Scientist who must Outgun a Mad Scientist in A Jet Boat"}, {"film_id": 10, "title": "ALADDIN CALENDAR", "description": "A Action-Packed Tale of a Man And a Lumberjack who must Reach a Feminist in Ancient China"}, {"film_id": 11, "title": "ALAMO VIDEOTAPE", "description": "A Boring Epistle of a Butler And a Cat who must Fight a Pastry Chef in A MySQL Convention"}, {"film_id": 12, "title": "ALASKA PHANTOM", "description": "A Fanciful Saga of a Hunter And a Pastry Chef who must Vanquish a Boy in Australia"}, {"film_id": 13, "title": "ALI FOREVER", "description": "A Action-Packed Drama of a Dentist And a Crocodile who must Battle a Feminist in The Canadian Rockies"}, {"film_id": 14, "title": "ALICE FANTASIA", "description": "A Emotional Drama of a A Shark And a Database Administrator who must Vanquish a Pioneer in Soviet Georgia"}, {"film_id": 15, "title": "ALIEN CENTER", "description": "A Brilliant Drama of a Cat And a Mad Scientist who must Battle a Feminist in A MySQL Convention"}, {"film_id": 16, "title": "ALLEY EVOLUTION", "description": "A Fast-Paced Drama of a Robot And a Composer who must Battle a Astronaut in New Orleans"}, {"film_id": 17, "title": "ALONE TRIP", "description": "A Fast-Paced Character Study of a Composer And a Dog who must Outgun a Boat in An Abandoned Fun House"}, {"film_id": 18, "title": "ALTER VICTORY", "description": "A Thoughtful Drama of a Composer And a Feminist who must Meet a Secret Agent in The Canadian Rockies"}, {"film_id": 19, "title": "AMADEUS HOLY", "description": "A Emotional Display of a Pioneer And a Technical Writer who must Battle a Man in A Baloon"}, {"film_id": 20, "title": "AMELIE HELLFIGHTERS", "description": "A Boring Drama of a Woman And a Squirrel who must Conquer a Student in A Baloon"}]

### SQL Injection Example

In [19]:
film_id = input("Enter a film id: ")

In [20]:
print(film_id)

4; TRUNCATE TABLE film2;

In [21]:

# Connect to the database
import json


con = pymysql.connect(host='167.71.90.83',
                             user='testUser',
                             password='testUser123!',
                             db='sakila',
                             cursorclass=pymysql.cursors.DictCursor)
data = []
try:

    with con.cursor() as cur:
        qry = "SELECT * FROM film WHERE film_id = " + film_id + ";"
        print(qry)
        cur.execute(qry)

        rows = cur.fetchall()

        for row in rows:
            film = {}
            film['film_id'] = row['film_id']
            film['title'] = row['title']
            film['description'] = row['description']
            #print(row['film_id'], row['title'], row['description'])
            data.append(film)

finally:

    con.close()
    
print(json.dumps(data))

SELECT * FROM film WHERE film_id = 4; TRUNCATE TABLE film2;;

ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRUNCATE TABLE film2' at line 1")

### Escaping parameters / Parametrized Queries

In [10]:
uname = input("Please enter your user name: ")
password = input("Please enter your password: ")

q = "SELECT * FROM users WHERE uname = '" + uname + "' AND password = '" + password + "'";
print(q)

SELECT * FROM users WHERE uname = 'dbabichenko' AND password = 'test123'

In [12]:
emp_no = input("Please enter employee number: ")
q = "SELECT * FROM employees WHERE emp_no = " + emp_no;
print(q)

SELECT * FROM employees WHERE emp_no = 1; DROP TABLE employees; //

In [ ]:

# Connect to the database
con = pymysql.connect(host='159.65.239.201',
                             user='testUser',
                             password='testUser123!',
                             db='sakila',
                             cursorclass=pymysql.cursors.DictCursor)


film_id = 1 #"1; DELETE FROM film; #"
title = 'ACADEMY DINOSAUR'

#qry = "SELECT * FROM film WHERE "
#qry += "film_id = " + str(film_id) + " AND title ='" + title + "';"

#print(qry)


try: 

    with con.cursor() as cur:
        cur.execute('SELECT * FROM film WHERE film_id=%s AND title=%s', [film_id, title]) 
        
        rows = cur.fetchall()

        for row in rows:
            print(row['film_id'], row['title'], row['description'])
finally:

    con.close()

SELECT * FROM film WHERE film_id = 1; DELETE FROM film; # AND title ='ACADEMY DINOSAUR';

"\ntry: \n\n    with con.cursor() as cur:\n        cur.execute('SELECT * FROM film WHERE film_id=%s AND title=%s', [film_id, title]) \n        \n        rows = cur.fetchall()\n\n        for row in rows:\n            print(row['film_id'], row['title'], row['description'])\nfinally:\n\n    con.close()\n\n"

### Insert a row with PyMySQL

In [28]:
con = pymysql.connect(host='143.198.177.53',
                             user='testUser',
                             password='testUser123@!@!',
                             db='employees',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)



try: 

    with con.cursor() as cur:
        q = "INSERT INTO employees (emp_no, birth_date, first_name, last_name, gender, hire_date) "
        q += "VALUES (%s,%s,%s,%s,%s,NOW());"

        cur.execute(q, (1, '1977-10-10', 'Dmitriy', 'Babichenko', 'M')) 
        con.commit()

finally:

    con.close()

### Update a MySQL table with PyMySQL

In [27]:
con = pymysql.connect(host='143.198.177.53',
                             user='testUser',
                             password='testUser123@!@!',
                             db='employees',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)



try: 

    with con.cursor() as cur:
        qry = 'UPDATE books SET first_name = %s WHERE book_id = %s'

        cur.execute(qry, ('Bob', 3)) 
        con.commit()

finally:

    con.close()

### Delete from a MySQL table with PyMySQL

In [28]:
con = pymysql.connect(host='143.198.177.53',
                             user='testUser',
                             password='testUser123@!@!',
                             db='employees',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)



try: 

    with con.cursor() as cur:
        qry = 'DELETE FROM books WHERE book_id = %s'

        cur.execute(qry, (3)) 
        con.commit()

finally:

    con.close()